### ISSUE TITLE
Serialize byte arrays in Credential as base64url

### ISSUE THREAD

**Issue by robyoder** [kanidm/webauthn-rs#140]
I want to store my `Credential` objects as JSON blobs in my database, but when I serialize with serde, they look like this:

`{"cred":{"key":{"EC_EC2":{"x":[129,240,14,182,168,233,84,130,193,153,41,150,229,170,167,169,161,175,69,53,36,193,242,45,73,134,10,218,38,119,254,87],"y":[216,75,187,80,142,159,27,229,85,178,202,159,19,214,211,171,41,6,183,191,84,32,48,212,120,146,100,218,9,206,171,148],"curve":"SECP256R1"}},"type_":"ES256"},"counter":0,"cred_id":[18,26,94,224,58,85,138,162,253,43,134,242,86,255,49,15,193,217,126,241],"verified":true,"registration_policy":"discouraged"}`

Those byte arrays would be much more compact as base64 (my preference would be base64url without padding), but it seems like there's no way for me to make that happen without reimplementing the entire structure manually.

**Comment by Firstyear** [comment]
@robyoder What version are you running? Is this git master or the latest release? I think recently we made some changes to some oof these parts to help base64 some fields in the serialisations.

**Comment by robyoder** [comment]
0.3.2. But `COSEEC2Key` [looks the same](https://github.com/kanidm/webauthn-rs/blob/6f8ca8c7e133ed17fdf709579056acf1bcf5afdd/webauthn-rs-core/src/interface.rs#L110), using the standard derived serialization of `Vec<u8>` for `x` and `y`.

I do see that as of #100, `CredentialID` has changed from `Vec<u8>` [to `Base64UrlSafeData`](https://github.com/kanidm/webauthn-rs/blob/6f8ca8c7e133ed17fdf709579056acf1bcf5afdd/webauthn-rs-proto/src/options.rs#L12). Bringing that change to all of the byte arrays inside `Credential` would be perfect. 👌

**Comment by Firstyear** [comment]
@robyoder Will do, that shouldn't be difficult. I'll also add compatibility conversions in there too. So feel free to keep using 0.3.2 for now, and there will be a pathway to "upgrade" to the newer format. 0.4 is going to be quite a substantial change and improvement :) 

The 0.4 release will likely be early august I expect, as there is quite a bit we are currently doing inside the project, and in related projects. 

Of course, if you want it sooner, feel free to create a PR, but otherwise, leave it with me. If you have any other feedback, thoughts on input, we'd love to hear it!

**Comment by robyoder** [comment]
Thanks! I just installed from master, and I'm running into a few difficulties, so I may have more feedback soon. 😄

**Comment by Firstyear** [comment]
No problem! I'm not surprised about the troubles, master is currently a work in progress, and still evolving. So your feedback about it would be really appreciated. Just remember, master is still in flux so it's not guaranteed all the serialisation formats will be stable until 0.4 is out. :)
