### ISSUE TITLE
Run and conform to the fido webauth conformance tests

### ISSUE THREAD

**Issue by Firstyear** [kanidm/webauthn-rs#16]
Test that we pass these! it will likely force us to implement other attestation formats, but may also shake out any other assumptions we make (especially around the JS). This is a pretty big task, so it would also be good to add more test cases for different types first to move us closer to this baseline.

**Comment by Firstyear** [comment]
I think the major tasks outstanding here are:

* TPM attestation
* Android Attestation
* RS384, RS512, PS*, ECDSA_384, ECDSA_512, and ED25519 crypto
* Extensions

I think once those are implemented, we'd be most of the way there, then it will be a case of running the conformance suite to catch anything we missed. We should consider that any test we fail can become a test vector within the codebase to ensure continued conformance.

**Comment by Firstyear** [comment]
Okay, interestingly due to the recent security discoveries with regard to userVerification me may not be able to pass the FIDO conformance suite. I would prefer to be "correct" that "conformant" in this case, but we'll see how it goes during the test.

**Comment by madwizard-thomas** [comment]
The FIDO conformance tests do not always align with the WebAuthn spec. One issue I came across is that the conformance tests do not require user presence (UP) to be always set (they call it 'silent authentication' which WebAuthn does not allow), while WebAuthn is clear about this. To solve these kind of issues I used a policy/config object that allows to toggle such behavior (eg `setUserPresenceRequired`, while sticking to the WebAuthn spec rather than FIDO by default). Also I have come across a fair amount of bugs in the conformance tests as well.

**Comment by Firstyear** [comment]
Hmmm that's an interesting thought. We could have a 'fidoConformance' flag that we toggle if it's required to change some behaviour (but off by default) especially if we deviate from the conformance tests.

**Comment by madwizard-thomas** [comment]
Is there an executable to test webauthn-rs with the conformance tests already?

**Comment by Firstyear** [comment]
No, we don't currently have that. It would be interesting for certain to port the conformance tests into our test suite to execute them there automatically, but so far it's not been a critical issue as most people care more the library working :)

**Comment by Firstyear** [comment]
It's unclear if we'll ever be able to do or bother to do this, and no one seems to care much if it's compliant anyway
