### ISSUE TITLE
dependency serde_cbor is unmaintained

### ISSUE THREAD

**Issue by mtnking** [kanidm/webauthn-rs#186]
The dependency serde_cbor is unmaintained and is flagged on a "cargo audit". The serde_cbor maintainer recommends moving over to ciborium or minicbor. In my experience, the former is an easy replacement (though ymmv).

**Comment by Firstyear** [comment]
Thanks @mtnking, we know this. @micolous and I were talking about this recently and what to do. It's not as simple as it seems here though because many of the structures in webauthn need to work both for json *and* cbor. Since only ciborium implements that we'd need to choose that library. But it's not a simple rewrite either. It would be a huge investment of time and work. And to make it worse, Mozillas https://github.com/mozilla/authenticator-rs library which backs webauthn-authenticator-rs, and is used in firefox also relies on serde cbor. 

I think that the fact the library is "unmaintained" isn't a huge red flag, but cargo-audit now reports it as a problem which is going to create noise. 

cc @msirringhaus - this is going to be a problem in the future too on the moz side, so we need to consider what we do here.

**Comment by mtnking** [comment]
A totally fair and not unexpected response, thanks for taking the time. I
had just finished purging it from my repo in favor of ciborium, so it
seemed a good time to float the issue upstream. While I don't necessarily
think it's a huge red flag today either, eventually its orphaned status
will likely become an issue as Rust & the ecosystem move forward and
change. You already have it on your radar, which is most of what I was
hoping to achieve. Thanks again.

**Comment by Firstyear** [comment]
Thanks for raising it! The two major options today are:

* Swap to ciborium, and take the time to do the "rewrite" of pretty much everything in the crate. Doesn't really help authenticator-rs though.
* Take over ownership of serde-cbor - this also is in our best interest but potentially the interest of mozilla, so they could contribute too since they are already dependent on it.

**Comment by robjtede** [comment]
I'd be interested in helping with a team-up if serde-cbor can be revived.

**Comment by Firstyear** [comment]
That sounds good @robjtede. @micolous @msirringhaus are the other two interested parties in this (former is a contributor to this project, latter is a contributor to mozillas authenticator-rs library). 

Would you two (micolous, martin) be open to this? I think within the webauthn space for rust this will be something we should investigate.

**Comment by msirringhaus** [comment]
Yes, I'd be open to this.
From the point of view of authenticator-rs, we wouldn't need to touch it at all, except in two cases:
1.) There is some CVE in the crate or its dependencies
2.) Firefox bumps its vendored rust-crates and we would need to update dependencies used in serde_cbor.

But since the deps are minimal, I don't see much work there from the auth-rs side of things.

Not sure if other projects need actual feature development on this or not?

**Comment by Firstyear** [comment]
Within the scope of auth-rs I think @micolous found some changes to serde-cbor that could improve the ctap interactions. 

@robjtede What ways are you using serde-cbor if I can ask? Would you be okay with kanidm project having the repo and you to be a collaborator?

**Comment by robjtede** [comment]
Mostly through webauthn at the moment but also trialing it as an alternative to JSON messages for our websocket gateway.

Yeah no qualms about the org setup.

**Comment by Firstyear** [comment]
Okay, my thinking is we clone https://github.com/pyfisch/cbor to github.com/kanidm, then if we publish to crates.io we should do it as an alternate name (serde_cbor2 ? Open to suggestions). That will allow the existing serde_cbor to remain, and if users choose to swap to the updated serde_cbor they can with a line like:

```
serde_cbor = { version = "0.12.0", package = "serde_cbor_2" }
```

So we just need to chose a name for the fork and I think we are good to go. I'll allocate @robjtede @msirringhaus and @micolous write permissions. Anything else we need to go over?

**Comment by robjtede** [comment]
I'm happy with just `serde-cbor2` if the plan is to have ownership transfer of `serde-cbor` at some point.

**Comment by Firstyear** [comment]
Okay, I have started this process now. I think there are some initial housekeeping tasks to do in the project before we make an "initial" release at current status-quo (looks like no-std is broken?) but the ball is rolling. Thank you all!
