### ISSUE TITLE
Rethinking the feature `danger-allow-state-serialisation`

### ISSUE THREAD

**Issue by Mythra** [kanidm/webauthn-rs#187]
While updating webauthn-rs from 0.3 -> 0.4 I noticed the same thing as #184 where the removal of `serde(Serialize, Deserialize)` from states meant they could no longer be stored in the database, cache, or anything along those lines. As far as I can tell the only place you can store it _without_ enabling the flag in some sort of `HashMap`. *Even both examples needs to enable it in order to actually provide full functionality.*

I understand the thought behind making it a feature, and making it sound scary with "danger-" in the name of the feature. So users have to be aware of the client side warnings before enabling a potential buggy case.

However, if even the most basic examples have to enable this feature the chance someone jumps into a codebase by someone who has it enabled because of necessity becomes very high. Not to mention it adds quite a bit of friction to users just jumping in. Since they can't follow the big bold warning labels that say "you must store this on the server side" without finding a complete separate feature (for example the docs: https://docs.rs/webauthn-rs/0.4.5/webauthn_rs/struct.Webauthn.html#method.start_securitykey_registration which mention the warning but don't mention the serialization features).

I'm hoping to open some discussion around how we can lower the friction, while hopefully keeping similar amount of warnings. Perhaps some ideas might be like:

 - adding in features for specific databases (such as implementing `#[sqlx::Type]` if you enable a `sqlx` feature, `#[SqlType]` for a `diesel` features, etc.
 - enabling the feature by default, but changing method names to be more clear something is not safe for the client side. (or just trusting the documentation).

These are just basic ideas, and I'm sure there are much smarter ones. I just really want to open a discussion somewhere.

**Comment by Firstyear** [comment]
Thanks for opening up the discussion @Mythra! Honestly it's a really hard balance. A huge motivator of this library is to make "webauthn impossible to hold wrong", because there really are so many ways to ... well, hold it wrong. But it also needs to be usable as you completely and correctly point out.

The reason we added this flag, was because someone came to me with example code that allowed un-bounded replay attacks using this library. We also saw and identified possible CVE's in other webauthn implementations not using this library due to the same fault.

So the decision was that yes, serialisation is absolutely still needed, but it does need a guard rail that says "look, there are ways to mess this up". 

I think the idea to add a "diesel" feature that add's the sqlx feature or something else like that would be really good - and welcome, if that would make it easier, because it also guides people in to a way that is 'easy to use' but lacks the ability to accidentally create replay attacks. 

I think as well, improving the start_registration methods to mention this is also a good idea.

But I'm not sure about enabling this by default, because that's how it "used to be" and allowed someone to step on a pretty horrible security exploit. Forcing people to look into "why" a feature exists to get them to read what is happening is also good so that people are aware of the handling risks (just like the unsafe key word in rust itself). 

@yaleman do you have any ideas?

**Comment by yaleman** [comment]
I guess the question is, when **wouldn't** you enable the feature flag, other than test cases and arbitrary example code? If all users are going to end up enabling it to be able to use the crate, then it should be the default.

Making the documentation more explicit is definitely required, random thoughts below:

1. [SecurityKeyRegistration](https://docs.rs/webauthn-rs/0.4.5/webauthn_rs/prelude/struct.SecurityKeyRegistration.html) is the main one that could do with a big banner around enable-the-feature-to-do-the-thing, since it's the thing you'd want to serialise, as far as I can tell.
2. Update the other warning banners to link properly to the struct, and (maybe?) mention the feature. I say maybe because ending up with big banners everywhere that we have to remember to update seems painful, and banner-blindness is also a thing.
3. Move the "allow serialisation" section in the features docs to be the first one, and mention it in the "getting started" since it'll be a common feature that most folks will want/use. It's also way more important for someone to notice while skimming the docs than the other things, and attention is in short supply 😇 

There's a [docs link](https://docs.rs/crate/webauthn-rs/0.4.5/features) for feature flags, is there some way of putting text in there?

**Comment by Firstyear** [comment]
Well, believe it or not it *is* very easy/possible to not need to enable this feature flag. In fact kanidm doesn't use it at all. The reason it's often used is in simpler setups when you have in-memory sessions with cookie-keys, the traits bounds require serialisation even if it's "kinda" not used. 

And when it *was* the default we saw examples of people using the feature incorrectly and opening up to CVE's which goes against the ideal of this library "forcing secure defaults". So I still think it can't be a default, because by not being a default, we have people need to acknowledge the risks and make informed decisions.

So I think make the docs better is probably the way to go here. 

It's not just security key registration, it's all the registration types that need it. But yeah, the warning banners could be better. I always have issues with rust-docs I can't find docs on how to make the rust docs and how to make links work. But yeah, moving allow serialisation to the first feature is a good idea.

**Comment by Mythra** [comment]
Perhaps we could create examples and point to how it is ideally used without serialization, especially if it's easy.  It's certainly not clear to me how I'd keep it around besides say -- just keeping the variable in memory, which then means it'd be incredibly hard/impossible to make it highly available web app. What happens when the server say reboots for a deploy during the authentication loop?

So if there are easy ways to keep this server side in a way that'd work where most people are, I know an example here would really help me, and presumably others (especially because the current examples do use the "bad" flag). I think just because it can be done without the flag, doesn't necessarily mean it'll be easy for everyone, and we should try to identify that balance based off of where people actually are, not any one project, or whether it can technically be done.

It also sounds like there are some other documentation ideas, and still sounds like the DB feature approach may be viable, but maybe we can avoid those features by having a really good example that docs can point too.

**Comment by Firstyear** [comment]
@Mythra We've significantly improved the docs, and I want to implement one more feature and I'll publish 4.6 so that docs.rs updates. Do you have anything else you might like to see here?

**Comment by Mythra** [comment]
Hey, sorry it took me a bit to get back to this! I appreciate the doc updates here, I think it would still be nice to look at building in some built in serialization for databases, that would mean you don't have to enable any "danger-" flags, but I'm happy to keep that as a separate feature request.
