### ISSUE TITLE
Incorrect usage of feature flags

### ISSUE THREAD

**Issue by Ofenhed** [kanidm/webauthn-rs#234]
Quote from [doc.rust-lang.org](https://doc.rust-lang.org/cargo/reference/features.html):
> […] features should be additive. That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features. A feature should not introduce a [SemVer-incompatible change](https://doc.rust-lang.org/cargo/reference/features.html#semver-compatibility).

However, looking at the  [danger-user-presence-only-security-keys feature](https://github.com/kanidm/webauthn-rs/blob/2af91a735b8f5c6a6f577554c633b73fe280c4ff/webauthn-rs/src/lib.rs#L661-L665), enabling the feature does not give additive functionality, but instead alters the existing function. Since a library is compiled with a superset of all features requested by an application or any of its dependencies, this means that a user may get the flag activated unknowingly by a dependency and be unable to get the default behavior without changing or removing the library.

**Comment by Firstyear** [comment]
Hmmmm this is a bit of a puzzle. I think you are right that this may not be a correct interpretation of the features since it's "changing a behaviour" rather than additive. But one could also see it as "additive" since it expands the way that the devices work. Saying this, the alternative is to use RUSTFLAGS with cfg flags, but these are wildly inaccessible and problematic in their own right. I think there really is no good option here to make this play nicely. 

We also don't want to make it to easy for people to access this feature, which is why it's not a default. 

Perhaps the correct answer is to make the feature expose a function on the WebauthnBuilder struct, which then the person needs to call into. That way if a lower level library enables this feature, it doesn't automatically get used since you still need to call the flag on the builder. 

Regardless of what we choose, we already have a major production user using this so we'd need a major version change to alter this regardless. (cc @devsnek for thoughts).

**Comment by devsnek** [comment]
@Firstyear I think as long as the functionality remains somehow, any sort of configuration or features or functions or whatever is needed would be fine.

**Comment by Ofenhed** [comment]
This was preemptively closed, see my [comment](https://github.com/kanidm/webauthn-rs/pull/235#discussion_r1048161909).

**Comment by Firstyear** [comment]
@Ofenhed There is no comment from that link? Why do you think this was closed too soon?

**Comment by Ofenhed** [comment]
Strange, it's stuck at pending...

> The same feature flag behavior still exist on line 765.

**Comment by Firstyear** [comment]
> Strange, it's stuck at pending...
> 
> > The same feature flag behavior still exist on line 765.

Thanks I missed this. I'll do a fixup.
