### ISSUE TITLE
start_passkey_registration() now requires a UUID for user ID

### ISSUE THREAD

**Issue by benwis** [kanidm/webauthn-rs#277]
Previously, the user_id for start_passkey_registration took a &str, and we used it with a non UUID unique user key. Now that function requires the use of a UUID ID. 

Is that intended? I'm now stuck between adding a unique UUID to our unique ID for webauthn-rs, pinning an old version, or hoping we can open up that type def again.

Thanks!

**Comment by Firstyear** [comment]
I think when you first used the feature @benwis the passkey wrapper was still a bit "in dev/preview" so I'm sorry about the change. I think you should add the UUID here. There are some good reasons to do so, if you want I'm happy to explain. The primary being that the unique_id field, especially with resident keys that certain people are pushing is an id that *can never be changed* so if we had of left it as &str then we risked people putting in PII into that field. We made it a UUID to force "best practice" from API users, so that it was "impossible to hold wrong". 

If we hadn't the risk was people would put in things like emails/usernames, and then accounts could never change their usernames/ids for risk of breaking them which causes issues for women, dv victims, transgender and other people who need to change their names.

Anyway, so I think the best thing is to add the UUID here. We don't plan to change it after this, and it will continue to work and be supported with future resident key stuff.

Is that all good?

**Comment by benwis** [comment]
It's a bit frustrating, but I somewhat understand. I think it is a bit limiting though, and perhaps not the right mechanism? What if ID is a ULID or a nanoID or some other acceptably random non-UUID type? 

The project I'm working on uses nanoIDs, and I'm personally waiting for UUID v7 to be stable. At the end of the day, I can add one into the table and make changes.

**Comment by Firstyear** [comment]
It's kind of meant to be limiting though, because if we just asked for uni bytes like the lower level core library does, people will just submit name.as_bytes() instead, this at least forces people to do the right thing. 

I would be open to changing it to an enum of unique identifiers though, I don't know much about nanoID's though. So I'd want to look into that first to be sure of how they work.

**Comment by Firstyear** [comment]
https://docs.rs/nanoid/0.4.0/nanoid/ <- this crate?

**Comment by benwis** [comment]
Yeah, I learned about it from this: https://planetscale.com/blog/why-we-chose-nanoids-for-planetscales-api
But I also have a client using ULIDs
https://docs.rs/ulid/latest/ulid/
And someone is probably doing something else

**Comment by Firstyear** [comment]
The main thing I want to avoid is just "letting people set arbitrary bytes". The right thing should be the easy thing, and uuid is "easy" from the start. But yeah, if you already went with one thing, it's a bit more annoying.

**Comment by benwis** [comment]
Yeah, I mean maybe it's something to go behind a feature flag or with unsafe in the name, feels a bit like the feature flag I had to add to get serialize/deserialize for the other structs

**Comment by Firstyear** [comment]
Hmmm would it be better as an enum in the unique_id field ? Or as seperate "start_passkey_registration_nanoid"? I'm also worried about "over populating" too many features and functions too .... @micolous what do you think?

**Comment by benwis** [comment]
An enum makes sense to me if you think all possible unique ID types can be defined. I'm not sure they can. And I don't think you want to do functions for every possibility. TBH, the nice thing about &str is that almost everything can be a &str. I'd probably put that function behind a feature flag myself, and let the user opt into it, but I'd be curios what others think

**Comment by Firstyear** [comment]
Again, the problem with &str is you may as well just make it &[u8] since that's what it is underneath in -core. And then we remove the "constraint" that forces developers to "do the right thing". Part of the reason for higher-lever webauthn-rs library is that it's just a thin veneer over -core, and it's designed to force correct choices that can never have negative impacts on users (even if that means it annoys developers sometimes). Effectively it's trading a bit of developer frustration for guaranteeing the best user experience (rather than the otherway around).

**Comment by micolous** [comment]
My opinion is that using `[&u8]`, `&str` or even `u128` for user IDs is very easy to hold wrong, and the "safe" API should avoid it.  On the other hand, I acknowledge that UUIDs aren't for everyone, and I don't want to normalise that people should use escape hatches in the API because they do something different.

At the end we want a library user to supply some random bytes as an identifier, we want enough of them that it avoids collisions, and that it's hard to stuff PII in there. I think including a _small_ number of types in the "safe" API which provide equivalent functionality to UUIDs is reasonable – but it needs to be pretty small (as every one of them is complexity we'd need to manage).

Another way we could do this is to allow `From<Uuid> + Into<Uuid>` as a parameter; but then you're stuck if you actually want to use the same binary and textual representation of that other identifier.

## Reviewing alternatives

UUIDv4 has 122 random bits.  UUID has ways to namespace and timestamp values to avoid collisions (the other versions), and they're all a fixed size (128 bits). UUIDs are a well-defined type in a bunch of programming languages and database systems, and have been around for a long time. UUIDs are also used in other parts of the library, so we already have to ship support for UUIDs no matter what.

The main downside is the canonical base16 presentation is very unwieldy to work with, and there are endianness issues to worry about if you don't use the random ones.

### NanoID

From reading [PlanetScale's NanoID blog post][0], it sounds like their primary concern with UUIDs is the human presentation of that value.

_PlanetScale's_ NanoID uses base36 (all digits + alpha) and a variable length. PlanetScale suggests using 12 characters, which ends up with a little more than a 62 bit random value (assuming all characters are used for random), and suggests the need to explicitly check for collisions.  Using base36 increases density, but there are characters which are easily confused (`1 I L`, `O 0`) which hinders readability.

Then there's also [another JavaScript implementation][2], which uses a base64 alphabet and a different fixed length, which may or may not be the same thing.  It is fixed length, but has similar issues to the PlanetScale version.

Both of these are designed to be used as a `&str`, and lack a binary representation.

I don't think NanoID is a suitable replacement for UUID: it's a variable width type which dramatically impacts its randomness, it lacks namespacing and timestamping which increase the likelihood of collisions, and has multiple incompatible implementations which have different representations.

### ULID

[ULIDs][1] address the length and readability issue with UUIDs, and use base32 to avoid confusing characters (unlike NanoID). It's also got 128 bits (48 bit timestamp + 80 bits random) which is at least _as good_ as a UUID.

https://github.com/dylanhart/ulid-rs has an implementation with a proper `Ulid` type.



[0]: https://planetscale.com/blog/why-we-chose-nanoids-for-planetscales-api
[1]: https://github.com/ulid/spec
[2]: https://github.com/ai/nanoid

**Comment by Firstyear** [comment]
Wouldn't it be possible to have ulid convert to a uuid in this case then since they are both 128bit?

**Comment by micolous** [comment]
That `ulid` Rust crate provides `From<Uuid>` and `Into<Uuid>` impls, so it's even easier. :)

**Comment by Firstyear** [comment]
So in that case, I think if ulid (which I think @benwis is using) have from+into uuid, then we don't have to do much here since they can just do .into()/from() where needed. 

If we were to change the api at all, it would be to have it take Into/From UUID as the traits instead IMO. Despite the flaws of them, they are still the best choice here IMO and extremely well established and cared for in the rust ecosystem.

**Comment by Firstyear** [comment]
Closing as this has been resolved
