### ISSUE TITLE
The behavior of "residentKey": "preferred" differs from that of "required" in Chrome browser

### ISSUE THREAD

**Issue by conr2d** [kanidm/webauthn-rs#298]
**Is your feature request related to a problem? Please describe.**

With the latest version of Chrome browser and https://webauthn.io, you can test webauthn registration process with the built-in virtual authenticator environment in browser developer tools.

You can create virtual authenticator with or without residentKey support, and you can find the results of registration with "residentKey": "preferred" and "required" are different.

|#||residentKey|requireResidentKey|registration|
|-|-|-|-|-|
|1|authenticator w/ residentKey support|"preferred"|false|success, residentKey|
|2|authenticator w/o residentKey support|"preferred"|false|success, no residentKey|
|3|authenticator w/ residentKey support|"required"|true|success, residentKey|
|4|authenticator w/o residentKey support|"required"|true|failed|

In scenario 4, registration process is stopped with the error message like "Your security key can't be used with this site", and the browser requests another authenticator.

**Comment by Firstyear** [comment]
I'm not sure what the issue is here? This is just specific to the chrome software test authenticator, but that's not reflective of reality either. 

What I think is happening here is the software authenticator either *does* support rk, or *does not*. So in each of the 4 scenarios you list here, the behaviours are "correct". 

But reality is different sadly, and you'll note that "preferred" results in a residentKey provided the authenticator supports rks. This is true of pretty much all devices today include ctap2.0 devices where you can *never delete an rk once it's created without a full device reset*.

So can you explain to me what the issue is you think is occurring? To me this all looks "expected".

**Comment by conr2d** [comment]
I see. In the discussion of #292, I read the comment that the behavior of "preferred" is same to that of "required" in modern browsers, so this issue report was just intended for providing information to dev team.

Since user doesn't need to remember even user ID with rk, I thought that rk is usually preferred, but it needs to provide a way to register with an authenticator that doesn't support rk.

However, as you mentioned, rk seems not a good option in real world cases, because there is no way to manage created rks in authenticator. There is no option to delete it without reset and the maximum number of rks is quite small. (e.g. Yubikey 5 only supports 25 discoverable credentials, but non-rk can be created as many as the storage capacity allows.)

**Comment by Firstyear** [comment]
Yep, this is exactly the issue. It's been discussed at length in the webauthn wg and other spaces, generally to the detriment of security keys. 

There are already cases where sites that force rks (such as microsoft azure) have caused peoples keys to fill up with credentials and they now are forced to use password + totp instead. 

So sadly as much as the username autocomplete could have been an opportunistic property with rk preferred/required, it is not something we can do because of the harms it causes to security key users.

The exception to this is apples keychain synced passkeys which are resident keys *even* when rk=discouraged. These will always allow that autocomplete in those cases.

We have experimented with conditional ui (the autocomplete tech) with this library and found it generally lacking in browsers - from poor ux/ui to a browser that had security vulnerabilities in their implementation. So far we believe that "resident keys" are not ready for their advertised usage of id autocomplete in these cases because of this. We will continue to check on this and the progress and once the ux is at a high enough level then we will ungate the opportunistic resident key support that we have developed.
