### ISSUE TITLE
Rethink the dangerous feature flags

### ISSUE THREAD

**Issue by Ofenhed** [kanidm/webauthn-rs#323]
**Problem description**
I think that the `danger-` feature flags is a dirty (and possibly dangerous) way to handle what you consider to be dangerous features, mainly for the following reasons:
- If you add dependencies which may use the same dependency as you do, then you don't control your feature flags for that dependency. You can choose which to include, but you can't exclude feature flags. I would also guess that many users wouldn't even know how to find which features are actually active for a dependency.
- Enabling a feature enables it in your entire project, and not only where you need it, which makes the library more dangerous to use everywhere, even if you're aware of the effects locally where you needed the dangerous feature.

**Solution**
I would suggest instead that you let the type system handle this problem for you. My draft of a solution:

- Create the struct `Dangerous<T>`, which is just a holder for a private `inner: T`.
- Move all dangerous functions defined for `impl OriginalType` into `impl<T: Borrow<OriginalType>> Dangerous<T>` or `impl<T: BorrowMut<OriginalType>> Dangerous<T>`.
- Add the trait `EnableDangerous` which implements `fn with_dangerous_features(&self) -> Dangerous<&Self>`, `fn with_dangerous_features_mut(&mut self) -> Dangerous<&mut Self>`, and `fn into_dangerous(self) -> Dangerous<Self>`.
- Add gated serialization support to the `CreationChallengeResponse` type:
    - Rename the type `CreationChallengeResponse` to `CreationChallengeResponseInner` and make the type `CreationChallengeResponse` a holder.
    - Derive `Deserialize` and `Serialize` for `CreationChallengeResponseInner`.
    - Implement `impl<T: Borrow<CreationChallengeResponse>> Serialize for Dangerous<T>` (which is just a callthrough to `CreationChallengeResponseInner`).
    - Implement `Deserialize` for `Dangerous<CreationChallengeResponse>`.
    - Implement `impl Dangerous<CreationChallengeResponse> { fn trust_challenge_response_source(self) -> CreationChallengeResponse; }`
- As enabling a feature flag should never be dangerous in itself, remove all `danger-` feature flags. For all feature flags which are conditional for library dependencies, rename the feature flag to not contain the `danger-` prefix instead of removing the flag.
- Blanket implementations:
    - `Dangerous<T>` implements `Deref<Target=T>`
    - `Dangerous<&mut T>` implements `DerefMut`

**Issues**
- This would be a breaking change (but likely with minimal migration), so this would have to be a major version update.
- Using the type `Dangerous<&T>` adds a level of indirection to using the type `T`, and using the type `Dangerous<T>` introduces annoying type juggling. I would assume (but may be completely wrong about this) that the compiler can remove this indirection for code such as `variable.with_dangerous_features().do_something_dangerous()`, but probably not if users start using `Dangerous<&T>` as parameters.

**Alternatives**
This is the only good alternative I've come up with to the feature flag system. Please feel free to suggest alternatives in this issue.

**Comment by Firstyear** [comment]
I think this issue is based on the idea that a lower-level library will be enabling these flags. Generally most users of this are the leaf application so they'll be the only controlling these flags. If an application was to re-export this library and enable these features, it's also probably for a reason and they are wrapping those functionalities in a way that makes them "safe".

I'm not sure that I like the trait idea, it gets really messy really fast. But I also don't want to do something like cfg flags since they require people to change every invocation of cargo/rustc.

There really isn't a good story in rust to solve this kind of problem I think, feature flags while not perfect are kind of the best option we have today I think. I think as well, until someone actually ran into this in production by accident, then it's just a "theory", and I'd rather not change things just on a theoretical maybe.

**Comment by Firstyear** [comment]
@micolous What do you think? you've been learning and doing a lot lately, so maybe you have some ideas?

**Comment by Ofenhed** [comment]
Ok, I'll give you a non-theoretical use case, which depends on en non-locality of feature flags. Say that you want to set up an administrative interface with WebAuthn support. This administrative interface is extremely important as it's used to administrate systems in customer environments, so it mustn't be administrated by anyone but a trusted few. This includes cases (as has happened multiple times in supply chain attacks) where an evil actor remotely controls their computers, and they may or may not already be logged in to the administrative interface. 

To somewhat mitigate this threat, you could use WebAuthn in User Presence mode on each database update. (In reality I'd create the request client side with Form data as part of the challenge, but let's pretend that we do the next best thing and don't use the ChallengeResponse to verify data integrity)

Now, the issue arises. Database updates, while sensitive, are very common. My security department will not accept that the challenge request mode on the administrative interface login is anything but User Verification, but I'm lucky that users are accepting that each database change requires that they touch their WebAuthn devices.

If I haven't misunderstand the feature flags system, this kind of layered security is not something that could possibly be done with webauthn-rs, because of the non-locality of the feature flags.

**Comment by Firstyear** [comment]
Right, but using a device in this mixed UV=required/UV=discouraged mode isn't something that webauthn-rs is intended for -  webauthn-rs is meant to be for focused, direct, simple use cases. In fact even the feature flag for security keys to be discouraged was only added as an exception for a single user. Having the ability to swap in/out UV and UP modes is actually a pretty big footgun that we don't want to expose. 

In the example you have here, if you want something this dynamic you should be using the webauthn-rs-core layer directly so you have absolute control of what you are doing. 

So I think that in this case with this kind of work flow you want, you should be using webauthn-rs-core directly. So it's my view that this isn't actually an issue/bug today. What do you think? @micolous ?

**Comment by micolous** [comment]
As ugly as it is, using `--cfg` would address the "feature poisoning" issue, and add an extra speed-bump around dangerous APIs.  But `webauthn-rs-core` is the package you want to use if you want full control over how those operations happen.

As for the use case of conditionally performing UV around privileged or sensitive operations, it's not that simple:

* All CTAP 2.1 and later devices with `alwaysUv = true` ([which *might* be the default - it depends on the vendor][0]) need UV *even if* `uv=discouraged`.
  * As an RP (via a web browser), you have no control (or direct visibility) over whether `alwaysUv` is set, unset or even supported.
  * Users _could_ configure their authenticator however they like... if they knew how! The platform tools for this are lacking (and something we're trying to address with `fido-key-manager`), and Windows makes it very difficult to do anything more than factory reset, set PIN, and enroll fingerprints (direct CTAP access requires Administrator rights).

* Platform authenticators always require UV *when it is available*. Those I've tested are:
  * Android platform authenticator (both local and synchronised)
  * iOS platform authenticator
  * Safari and Chromium on macOS (and when Touch ID is *not* available, it'll only fall back to password when `uv=required`)
  * Windows Hello with a TPM

In an enterprise setting, if you want to stop requiring users typing in PINs all the time, then use alternatives:

* Instead of each application running its own authentication with `uv=discouraged`, use a single-sign-on system or authenticated proxy.

* Issue authenticators with a fingerprint reader (with the caveat that there are accessibility issues with fingerprint readers, including motor control and dermatitis)

* Allow other types of platform biometric authenticators (with the caveat that these also have mixed results)

For those critical and sensitive administrative tasks, [require review from a second party][1]. Having a user enter their own PIN doesn't do a whole lot, and if they have to do it _all the time_, they might put their PIN in a macro.

One important attribute of a security-sensitive system is the consistency and perception of the user experience. If a user is *not* consistently prompted for UV, then they may believe the credential is insecure.

[0]: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-feature-descriptions-alwaysUv-authnr-actions
[1]: https://en.wikipedia.org/wiki/Two-man_rule

**Comment by Firstyear** [comment]
> As ugly as it is, using `--cfg` would address the "feature poisoning" issue, and add an extra speed-bump around dangerous APIs.

Yes, but then you have to have the --cfg flag on every invocation to cargo/rustc, making it "very hard" for users to opt into. 

> * All CTAP 2.1 and later devices with `alwaysUv = true` ([which _might_ be the default - it depends on the vendor](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#sctn-feature-descriptions-alwaysUv-authnr-actions)) need UV _even if_ `uv=discouraged`.
>   

Actually, this is also true since we set credprotect, you can't do UP only with webauthn-rs for most credentials we create.

> 
> In an enterprise setting, if you want to stop requiring users typing in PINs all the time, then use alternatives:
> 
> * Instead of each application running its own authentication with `uv=discouraged`, use a single-sign-on system or authenticated proxy.
> * Issue authenticators with a fingerprint reader (with the caveat that there are accessibility issues with fingerprint readers, including motor control and dermatitis)
> * Allow other types of platform biometric authenticators (with the caveat that these also have mixed results)
> 
> For those critical and sensitive administrative tasks, [require review from a second party](https://en.wikipedia.org/wiki/Two-man_rule). 

Or have a "sudo mode" similar to what github does before you can self-edit your account or projects. Effectively you re-authenticate for a short term privileged token that allows writes, and it expires within a few minutes. 

> Having a user enter their own PIN doesn't do a whole lot, and if they have to do it _all the time_, they might put their PIN in a macro.
> 
> One important attribute of a security-sensitive system is the consistency and perception of the user experience. If a user is _not_ consistently prompted for UV, then they may believe the credential is insecure.

**Comment by micolous** [comment]
> > For those critical and sensitive administrative tasks, [require review from a second party](https://en.wikipedia.org/wiki/Two-man_rule).
> 
> Or have a "sudo mode" similar to what github does before you can self-edit your account or projects. Effectively you re-authenticate for a short term privileged token that allows writes, and it expires within a few minutes.

The "sudo mode" wouldn't protect against a remotely-compromised endpoint.  However, just requiring UP doesn't mitigate the issue either:

* "nano" (in-port) keys are impossible to remove without touching the button (capacitive sensor).
* BTLE keys are easy to accidentally press in your pocket without realising.
* NFC keys left on a reader can trigger UP by instructing the transceiver to power cycle the card.
* USB keys with no button (eg: PlugUp Nitrokey) can trigger UP by bouncing the USB port power (though this requires administrative rights).
* Windows limits direct access to portable keys, provided they implement the specs correctly, do not add extra commands, and the malware isn't running with Administrator rights.
  * Using RDP makes this worse, because all the authentication attempts will appear to come from the Remote Desktop Client, rather than the browser or some malware.
* Linux, macOS and friends don't protect portable keys *at all*.
* macOS only protects platform keys when `uv=required` *or* Touch ID is available. When you close the lid on a Macbook, Touch ID is no longer available, and you can bypass UP.

Presuming it was possible to be enforced (which is only on Windows or with platform authenticators), _nothing_ provides context to the user for "please sign this action", so a malicious actor can always wait for the user to perform some administrative action, intercept and modify it, and the user will be none the wiser... even if you required UV!

-----

Given the nature of [the proposed use case][0], and thinking about it some more, "rethinking dangerous feature flags" feels [a lot like an XY problem][1]:

* Your actual goal sounds like it is that it should be easier to apply UV policies inconsistently: `webauthn-rs-core` is what you want. The existing `danger-*` features don't let you do that.

* The existing `danger-*` features are about adding functionality which you still have to [explicitly][3] [call][4] [functions][5] to use (which are documented).

  I don't believe that this violates [Cargo's principle of additive features][6] - but allowing inconsistent UV policies with a feature **would violate it**.

* The only _non-additive_ functionality [was for RSA-SHA1 support (which will be removed)][2], but this was via a `--cfg` flag, not a feature.

* Generally speaking, `webauthn-rs` is designed for use in (or very close to) binary targets, so acquiring transitive features along the way is difficult.

  While using `--cfg` could make it harder, using it is very tedious.

Finally, a `Dangerous` trait is _even easier_ to accidentally depend on than a transitive feature:
 
```rust
use webauthn_rs::*;
```


[0]: https://github.com/kanidm/webauthn-rs/issues/323#issuecomment-1560539181
[1]: https://en.wikipedia.org/wiki/XY_problem
[2]: https://github.com/kanidm/webauthn-rs/pull/250
[3]: https://github.com/kanidm/webauthn-rs/blob/2db3a1a873c8d316e4782c80d8dc4f5bd6d86233/webauthn-rs/src/lib.rs#L289-L297
[4]: https://github.com/kanidm/webauthn-rs/blob/2db3a1a873c8d316e4782c80d8dc4f5bd6d86233/webauthn-rs/src/interface.rs#L117-L130
[5]: https://github.com/kanidm/webauthn-rs/blob/2db3a1a873c8d316e4782c80d8dc4f5bd6d86233/webauthn-rs/src/interface.rs#L22
[6]: https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification

**Comment by yaleman** [comment]
IMO cfg flags are the worst of smells and shouldn't be used in this case. They're for when you really really really want an escape hatch for doing a weird thing you're not happy about, but must have an out; not for this use case - where features work fine for gating things.

**Comment by Ofenhed** [comment]
You're right about additive features, @micolous. I was stuck in the idea that the `danger-user-presence-only-security-keys` feature changed behavior, but I see now that it was put behind a function. I was stuck in the mindset of #234. This completely invalidates this issue.

I did find your insights on my example very interesting. Thank you for that. I was very disappointed to find that my YubiKey gladly signs `UserPresence: true` over NFC without touching. I also expected that the transport method would be part of the signed data. I knew the method wasn't perfect, but I absolutely expected it to be better than this... 😟

**Comment by Firstyear** [comment]
> I did find your insights on my example very interesting. Thank you for that. I was very disappointed to find that my YubiKey gladly signs `UserPresence: true` over NFC without touching. I also expected that the transport method would be part of the signed data. I knew the method wasn't perfect, but I absolutely expected it to be better than this... 😟

The user presence is implied by the device being placed on the reader itself. That's why you don't need the "touch" event in the nfc case.

Transports are *not* a signed element because they are a "client" extension, so the browser indicates the transport. It's also worth noting the browsers commonly get this data wrong, which is why we *do not* request or provide the results of transport in our credentials because it is misleading and often incorrect.

**Comment by micolous** [comment]
No worries, I'm happy we could help! :)

I didn't put the context together about #234; and yeah, reading this closer, I misunderstood the mechanics of the `Dangerous<T>` struct and `EnableDangerous` trait.

What your Yubikey is doing [is allowed by the spec][0] (emphasis added):

> For authenticators without a method to collect a user gesture inside the authenticator boundary other than through a power on gesture, the act of a user placing an NFC authenticator into **the NFC reader’s field is considered a user gesture that establishes user presence and provides [evidence of user interaction](https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#evidence-of-user-interaction)**. This powers-up the authenticator, who then starts an NFC powered-up timer, and sets an NFC userPresent flag to true. There is an associated NFC user presence maximum time limit of two minutes (120 seconds).

[0]: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#evidence-of-user-interaction

The trouble is that you can [control the NFC reader's field from software][1] (`dwInitialization = SCARD_UNPOWER_CARD`), so a smartcard can't tell the difference between the authenticator being moved in and out of the field by the user, vs. the NFC reader dropping the field, waiting a moment, and then turning it back on again. Unfortunately, there's no reasonable mitigation for that, and it's not possible to implement keep-alive / `UP_NEEDED` over the FIDO NFC transport layer (it's only over BTLE and USB HID).

The only security key I've seen which _required_ a button press to activate NFC is the [Hideez Key 4][2] (BTLE+NFC+USB), because it didn't implement [wake-on-field (power up the SoC on NFC field)][4]. Once the SoC is running (from battery or USB power), it does the same implicit-UP over NFC that Yubikey does.

The other BTLE+NFC+USB key I have ([Feitian MultiPass][3]) does not require a button press to activate NFC, nor do any of the NFC+USB keys I have, even when they have a mechanical button.

I wouldn't say that this makes the Hideez Key 4 better or worse than the others; just the others have designed the firmware and electronics differently. The nRF52840 SoC they're using [supports wake-on-field][4], so _at worst_ it could done in a future hardware revision.

[1]: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreconnect
[2]: https://hideez.com/en-au/products/hideez-key-4
[3]: https://www.ftsafe.com/products/FIDO/Multi
[4]: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52840%2Fnfc.html
