### ISSUE TITLE
Add EdDSA capabilities

### ISSUE THREAD

**Issue by zacknewman** [kanidm/webauthn-rs#399]
It would be nice if EdDSA curves were properly supported; and once supported, `webauthn_rs_proto::cose::COSEAlgorithm::secure_algs` added `COSEAlgorithm::EDDSA` to the returned `Vec`. Personally I would even like a way to prioritize such curves (e.g., Ed25519). I think that could be done in a "safe" way with something like `webauthn_rs::WebauthnBuilder::prefer_edwards_curves` which would allow developers to not have to specify specific curves.

**Comment by Firstyear** [comment]
It's not possible today. There are no rust cryptography libraries that are high quality enough, portable, *and* support the needed key hydration options. 

Optimally we want to stay within the openssl ecosystem, and that sadly doesn't allow recovering ed25519 keys from points. (rather, it allows recovery from points, but it's not the same point axis). 

>  I think that could be done in a "safe" way with something like webauthn_rs::WebauthnBuilder::prefer_edwards_curves

We already support the ability to set what algorithms you accept, so we don't need this flag.

Finally, almost no keys support ed25519. The exceptions are the FIPS validated yubikeys, and solokey/nitrokey. However, both solokey and nitrokey have security issues, meaning I don't consider their use "serious" for security purposes so any discussions of algorithms is completely pointless when your key is fundamentally flawed. 

As a result, we see no reason to implement ed25519 support at this time, nor do we feel a need to rush to support it.

**Comment by Firstyear** [comment]
> > It's not possible today. There are no rust cryptography libraries that are high quality enough, portable, _and_ support the needed key hydration options.
> > Optimally we want to stay within the openssl ecosystem, and that sadly doesn't allow recovering ed25519 keys from points. (rather, it allows recovery from points, but it's not the same point axis).
> 
> [`ed25519_dalek`](https://docs.rs/ed25519-dalek/latest/ed25519_dalek/) does not work? I find it to be high quality, and I believe it is portable.

We prefer openssl because of various compliance reasons that our library consumers have. 

> One can serialize the Y coordinate; and if for some reason you need the superflous X coordinate to be serialized, then you can derive it manually from the Y coordinate. What am I missing here?

That nothing magically supports that out of the box. 

> 
> > Finally, almost no keys support ed25519. The exceptions are the FIPS validated yubikeys, and solokey/nitrokey. However, both solokey and nitrokey have security issues, meaning I don't consider their use "serious" for security purposes so any discussions of algorithms is completely pointless when your key is fundamentally flawed.
> 
> Non-FIPS YubiKeys have supported Ed25519 since firmware 5.2.3 (the current firmware is 5.4.3). I have been using `sk-ssh-ed25519@openssh.com` on every SSH server I maintain for a while now with both the resident and non-resident key option with my YubiKey 5C (_not_ FIPS-validated).

Still, the point is there is very little compelling reason to prefer ed25519 over ecdsa today, and it's a large amount of work that has little gain for us.

I think right now this feature request is in "PR's welcome" - until we have a user with a strict compliance reason for it, then we might consider it but I doubt that will occur.

**Comment by Firstyear** [comment]
I did say PR's would be welcome. Yes most of the infrastructure is already there, and there are even *test* vectors in the repo, that currently just expect errors since we don't support this type. 

So provided you can do this with openssl, then no problem. 

My point was there was nothing compelling our team right now to pursue this feature on our own time, not that we wouldn't accept it. 
 
It's disappointing to learn about the confusing nature of the values in the specifications - this confusion was the very thing that trapped us in the past from implementing this type.

**Comment by Firstyear** [comment]
Github PR's are preferred, but if needed I'll accept a `git format-patch` output.

**Comment by Firstyear** [comment]
> I reordered `webauthn_rs_proto::cose::COSEAlgorithm`s such that `COSEAlgorithm::EdDSA` is first in any sequence to align with RFC 9053 (e.g., `COSEAlgorithm::secure_algs[0] == COSEAlgorithm::EdDSA`).

Where are you seeing this in rfc9053? It appears to make no recomendation for algorithm order preference.

**Comment by Firstyear** [comment]
As mentioned in the email, re-ordering the algos is a separate discussion.
