### ISSUE TITLE
Question: Is not implementing PartialEq or EqEq on some types intentional?

### ISSUE THREAD

**Issue by jtmorrisbytes** [kanidm/webauthn-rs#448]
**Is your feature request related to a problem? Please describe.**
I am storing CreationChallengeResponse from webauthrn_rs_proto in a situation that requires PartialEq. PartialEq is not implemented for this or any of its members. Is this intentional? 
**Describe the solution you'd like**
A description of what you'd expect to happen.

I would like to have partialeq implemented for this type

**Comment by Firstyear** [comment]
What do you mean by "storing" here? Per https://docs.rs/webauthn-rs/latest/webauthn_rs/prelude/struct.CreationChallengeResponse.html - "This is meant to be opaque, that is, you should not need to inspect or alter the content of the struct - you should serialise it and transmit it to the client only.".

Why do you need to store it at all? 

If we were to add PartialEq / Eq, it should be a default impl that always returns false (not equal) since there is no way to compare equality of this type.

**Comment by jtmorrisbytes** [comment]
I am still new to this library and was not aware of this when the question was posed. I was storing this type on the client side of my app temporarily between registration steps. Thank you for your time

**Comment by Firstyear** [comment]
Ahh you shouldn't need that, it's a very "ephemeral" thing. You get the CCR and immediately use it, it shouldn't need storing. :)
