### ISSUE TITLE
Failed to parse MDS

### ISSUE THREAD

**Issue by sycamoreoak** [kanidm/webauthn-rs#462]
### I did this

```
cd compat_tester/webauthn-rs-demo
cargo run 
```

(same issue for release mode)

### I expected the following

webauthn demo go brr

### What actually happened

```
2024-12-19T16:52:51.281585Z  INFO webauthn_rs_demo: Fetching MDS ...
2024-12-19T16:52:52.163261Z ERROR webauthn_rs_demo: Failed to parse MDS err=Serde
```

### Version (and git commit)

commit 1347c6ce943c7177070a9d5e5874dba144d06080

### Operating System / Version

latest and greatest ubuntu

### Any other comments

another FIDO schema change?

**Comment by Firstyear** [comment]
> maybe we could get some CI here to mitigate this in the future as well? In looking at the issues it seems that this has happened a number of times, and the MDS format is being updated fairly regularly.

The problem here btw is that fido are updating the MDS format *without announcement* and *without updating their own MDS format specification*. They are simply, "yolo, yeeting" new MDS values when they feel like. 

We also think given that this is meant to be the equivalent of a "CA root", strict parsing should be the norm. It's really important we get this right. 

But since we apparently are the only tool in the world that exists outside of fido to parse the MDS, we get the reports when it fails. When you run the tool, you can see all the errors that still exist in the MDS. We reported all of them to fido! They've had years to fix basic data entry issues and they simply haven't! So now they're just throwing out now MDS fields for the laughs, and we have to play whack a mole and respond, with no communication or recourse. 

The final nail here is *we want to help fido* but they won't let us because I as an individual would have to pay a significant sum of money to join, just so that I can actually have these issues heard.

**Comment by Firstyear** [comment]
Yeah, I'm merging it today and releasing too.

**Comment by Firstyear** [comment]
"that depends". If you're always pulling the latest mds and applying it, yes, you will cause a system to grind to a halt. I think the way most people are using this is "intermittent updates" of the MDS so they don't have these issues.

And as well, depends on your threat model - the main reason you would stress about MDS updates is the risk of a compromised authenticator, so you want to be able to remove it from the attestation lists ASAP. But depending on your risk profile, that also may not need to happen rapidly etc. So it's hard to say what the right answer is here.

**Comment by Firstyear** [comment]
> Do javascript implementations which consume the MDS also break when they change it?

I am not aware of any other MDS parser beside this one. Even fido were "shocked" that I wrote a parser when I told them. So I don't know. 

> As in an entire product line, right?

Yes. There are multiple compromised devices already that should not be used. Part of what makes this hard is that the MDS kind of "lies"about the situation, which is that if *any* firmware version of a device is compromised, you have to exclude all versions of that device, even if they have fixed firmware. The reason is that attestation doesn't provider the fw version to the provider, so you have to assume all devices are the broken one. There are some devices like yubikeys that have custom x509 fields for this, and I think there was some moves to add a fw field in the attestation data, but that doesn't help with all the devices that already exist and don't report their fw version.

**Comment by Firstyear** [comment]
> The merge worked and the specific issue referenced here is fixed, so thanks very much.

No problem. Sorry to seem so "negative" about this, but this has been an uphill battle with fido for a long time, and the vibe we get from them is they simply don't care unless you are a mega-corp who pays them money. :(
